"""Security-headers contract (backend/app/secheaders.py + its middleware).

Every response — SPA, assets, and API, success or error — must carry the CSP and
anti-framing/nosniff/referrer headers. The CSP is the second line of defense under
the LLM-markdown render surface, so this pins that it stays present AND restrictive
(no 'unsafe-inline'/'unsafe-eval' in script-src, framing denied).

Strict-Transport-Security is CONDITIONAL, not part of the always-on set: it must
appear only when the deployment's `app_public_url` is https, and never carry
`includeSubDomains`/`preload` (HSTS is host-scoped but PORT-agnostic, and the
app can itself terminate TLS on `:8000` with a self-signed cert while the same
host serves something else on :80 — see README's Self-hosting/HTTPS section).

APP_PUBLIC_URL is pinned explicitly here (http, matching the dev/CI default),
the same "test-env gotcha" workaround test_csrf.py/test_bodylimit.py already use:
a developer's real .env sets APP_PUBLIC_URL to an https address, which would
otherwise silently flip this whole file's default posture and mask the very
regression the http-posture tests below exist to catch.
"""
import os
import re
import sys
import tempfile
from contextlib import contextmanager
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

tmp = tempfile.mkdtemp()
os.environ["APP_DB_PATH"] = str(Path(tmp) / "app.db")
os.environ["ADMIN_EMAILS"] = "admin@example.edu"
DEFAULT_PUBLIC_URL = "http://localhost:8000"
os.environ["APP_PUBLIC_URL"] = DEFAULT_PUBLIC_URL
os.environ["COOKIE_SECURE"] = "false"

from fastapi.testclient import TestClient  # noqa: E402

from app.config import get_settings  # noqa: E402
from app.main import app  # noqa: E402
from app.secheaders import SECURITY_HEADERS  # noqa: E402

FAILURES = []


@contextmanager
def _public_url(url):
    """Temporarily point APP_PUBLIC_URL at `url` for the duration of the block,
    clearing the lru_cache'd get_settings() so a request made inside the block
    sees it. Restores the file's pinned http default on exit. Clearing the
    cache (rather than just editing os.environ) is deliberate: it is what
    forces the posture check to happen at REQUEST time — a middleware that
    instead computed its headers once at import would never see this change,
    which is exactly the bug shape being probed here (see module docstring
    and CLAUDE.md's note on this middleware's mounting)."""
    os.environ["APP_PUBLIC_URL"] = url
    get_settings.cache_clear()
    try:
        yield
    finally:
        os.environ["APP_PUBLIC_URL"] = DEFAULT_PUBLIC_URL
        get_settings.cache_clear()


def check(name, fn):
    try:
        fn()
        print(f"  ✓ {name}")
    except AssertionError as e:
        FAILURES.append(name)
        print(f"  ✗ {name}: {e}")


def test_all_headers_present_on_api_response():
    with TestClient(app) as c:
        r = c.get("/api/health")
        assert r.status_code == 200, r.status_code
        for key in SECURITY_HEADERS:
            assert key in r.headers, f"missing security header: {key}"


def test_csp_is_restrictive():
    with TestClient(app) as c:
        csp = c.get("/api/health").headers.get("content-security-policy", "")
    # The whole point of the CSP is a strict script-src: any 'unsafe-inline' or
    # 'unsafe-eval' here would let injected/inline script run and defeat it.
    assert "script-src 'self'" in csp, csp
    assert "'unsafe-inline'" not in csp.split("style-src")[0], \
        f"unsafe-inline must not weaken script-src: {csp}"
    assert "'unsafe-eval'" not in csp, csp
    assert "object-src 'none'" in csp, csp
    assert "frame-ancestors 'none'" in csp, csp
    assert "base-uri 'none'" in csp, csp
    # Chart export renders data: images; that source must be permitted.
    assert "img-src 'self' data:" in csp, csp


def test_anti_framing_and_nosniff_values():
    with TestClient(app) as c:
        h = c.get("/api/health").headers
    assert h.get("x-frame-options") == "DENY", h.get("x-frame-options")
    assert h.get("x-content-type-options") == "nosniff", h.get("x-content-type-options")
    assert h.get("referrer-policy") == "no-referrer", h.get("referrer-policy")


def test_headers_present_even_on_error_response():
    # Headers are stamped by the OUTERMOST middleware, so even a CSRF-refused 403
    # (generated by the inner middleware, never reaching a route) carries them.
    with TestClient(app) as c:
        r = c.post("/api/health", headers={"origin": "https://evil.example.com"})
        assert r.status_code == 403, r.status_code
        assert "content-security-policy" in r.headers, "error responses must be covered too"
        assert r.headers.get("x-frame-options") == "DENY"


def test_hsts_present_under_https_posture():
    """THE REGRESSION THIS CATCHES: a deployment reached over https (behind a
    TLS-terminating proxy/tunnel, or the app's own self-signed :8000 mode) must
    ship Strict-Transport-Security — without it, a browser has no signal to
    prefer https on a repeat visit, so a single stripped first request
    (sslstrip-style) has nothing stopping it. Also proves the header is derived
    at REQUEST time, not computed once at import: this file imports app.main
    under the http default, then flips posture and re-requests within the same
    process — a middleware that captured its headers once at import (rather
    than reading settings, like csrf.py's CSRFMiddleware already does per
    request) would still show no header here."""
    with _public_url("https://ipeds.example.edu"):
        with TestClient(app) as c:
            hsts = c.get("/api/health").headers.get("strict-transport-security")
    assert hsts, "no Strict-Transport-Security header under an https app_public_url"
    m = re.search(r"max-age=(\d+)", hsts, re.IGNORECASE)
    assert m and int(m.group(1)) > 0, f"missing or zero max-age: {hsts!r}"


def test_hsts_absent_under_http_posture():
    """THE REGRESSION THIS CATCHES: HSTS must stay CONDITIONAL on an https
    app_public_url — never hoisted into the unconditional header set. The
    default/dev posture (`make up`'s COOKIE_SECURE=false APP_PUBLIC_URL=http://
    localhost:8000, and any deployment without SSL_CERTFILE/SSL_KEYFILE per
    scripts/docker-entrypoint.sh) serves plain http, where telling a browser to
    force https would just break the site. This is the case that stops a future
    'simplification' from moving Strict-Transport-Security into
    SECURITY_HEADERS unconditionally."""
    with TestClient(app) as c:
        r = c.get("/api/health")
    assert "strict-transport-security" not in r.headers, \
        f"HSTS must not be sent under a plain-http app_public_url: " \
        f"{r.headers.get('strict-transport-security')!r}"


def test_hsts_has_no_subdomains_or_preload():
    """THE REGRESSION THIS CATCHES: `includeSubDomains`/`preload` widen the
    policy past this one host's :443 traffic — but HSTS is host-scoped and
    PORT-agnostic, and the README documents a deployment mode where the app
    terminates TLS itself on :8000 with a self-signed cert. A blanket policy
    from that mode would force https onto anything ELSE the same host serves
    on port 80. A reader who doesn't know this will 'complete' the header by
    adding the usual directives — this fails the moment either one appears."""
    with _public_url("https://ipeds.example.edu"):
        with TestClient(app) as c:
            hsts = c.get("/api/health").headers.get("strict-transport-security", "")
    assert hsts, "expected a Strict-Transport-Security header under https to inspect"
    assert "includesubdomains" not in hsts.lower(), hsts
    assert "preload" not in hsts.lower(), hsts


def test_all_headers_present_still_holds_under_https_posture():
    """THE REGRESSION THIS CATCHES: test_all_headers_present_on_api_response
    iterates SECURITY_HEADERS and demands every one of its keys on a response
    made under this file's pinned http default — so if a future change folds
    the conditional Strict-Transport-Security key into that always-applied
    dict, THAT (unmodified) test starts demanding a header the http posture
    deliberately withholds, and goes red. This test locks the other half of
    the same arrangement: re-running the identical check under an https
    posture must ALSO keep passing, which only holds if
    strict-transport-security never joined SECURITY_HEADERS at all (a
    conditional membership would make this pass while the http-posture run
    above fails, and vice versa — both must hold together)."""
    with _public_url("https://ipeds.example.edu"):
        test_all_headers_present_on_api_response()


def test_the_openapi_schema_and_docs_are_not_served():
    """FastAPI serves /docs, /redoc and /openapi.json UNAUTHENTICATED by
    default. On a private, allowlisted app that handed any caller the complete
    schema of all 31 admin endpoints plus every request body model -- measured
    at 41,893 bytes with no session. Not an authz bypass (every admin route is
    gated), but it is the whole attack surface, for free.

    Pinned because the fix is three kwargs on the FastAPI() constructor:
    re-adding a bare `FastAPI(title=..., lifespan=...)` silently restores the
    leak, and nothing else in the suite would notice. The SPA catch-all serves
    index.html for unknown non-/api paths, so the assertion is that the JSON
    schema is GONE, not that the path 404s."""
    with TestClient(app) as c:
        for path in ("/openapi.json", "/api/openapi.json"):
            r = c.get(path)
            body = r.text
            assert '"openapi"' not in body and '"paths"' not in body, \
                f"{path} still serves the OpenAPI schema ({len(body)} bytes)"
        for path in ("/docs", "/redoc"):
            body = c.get(path).text.lower()
            assert "swagger" not in body and "redoc" not in body, \
                f"{path} still serves API documentation"


def run():
    print("Security-headers contract:")
    check("all security headers present on an API response",
          test_all_headers_present_on_api_response)
    check("CSP is restrictive (strict script-src, no unsafe-*, framing denied)",
          test_csp_is_restrictive)
    check("anti-framing + nosniff + referrer values", test_anti_framing_and_nosniff_values)
    check("headers present even on a refused (403) response",
          test_headers_present_even_on_error_response)
    check("Strict-Transport-Security present under an https posture",
          test_hsts_present_under_https_posture)
    check("Strict-Transport-Security absent under the default http posture",
          test_hsts_absent_under_http_posture)
    check("the OpenAPI schema and docs UIs are not served",
          test_the_openapi_schema_and_docs_are_not_served)
    check("Strict-Transport-Security carries no includeSubDomains/preload",
          test_hsts_has_no_subdomains_or_preload)
    check("all-headers-present check still holds under an https posture too",
          test_all_headers_present_still_holds_under_https_posture)
    print()
    if FAILURES:
        print(f"{len(FAILURES)} contract(s) FAILED: {FAILURES}")
        sys.exit(1)
    print("ALL SECURITY-HEADERS TESTS PASSED")


if __name__ == "__main__":
    run()
