"""Security-headers contract (backend/app/secheaders.py + its middleware).

Every response — SPA, assets, and API, success or error — must carry the CSP and
anti-framing/nosniff/referrer headers. The CSP is the second line of defense under
the LLM-markdown render surface, so this pins that it stays present AND restrictive
(no 'unsafe-inline'/'unsafe-eval' in script-src, framing denied).
"""
import os
import sys
import tempfile
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

tmp = tempfile.mkdtemp()
os.environ["APP_DB_PATH"] = str(Path(tmp) / "app.db")
os.environ["ADMIN_EMAILS"] = "admin@example.edu"

from fastapi.testclient import TestClient  # noqa: E402

from app.main import app  # noqa: E402
from app.secheaders import SECURITY_HEADERS  # noqa: E402

FAILURES = []


def check(name, fn):
    try:
        fn()
        print(f"  ✓ {name}")
    except AssertionError as e:
        FAILURES.append(name)
        print(f"  ✗ {name}: {e}")


def test_all_headers_present_on_api_response():
    with TestClient(app) as c:
        r = c.get("/api/health")
        assert r.status_code == 200, r.status_code
        for key in SECURITY_HEADERS:
            assert key in r.headers, f"missing security header: {key}"


def test_csp_is_restrictive():
    with TestClient(app) as c:
        csp = c.get("/api/health").headers.get("content-security-policy", "")
    # The whole point of the CSP is a strict script-src: any 'unsafe-inline' or
    # 'unsafe-eval' here would let injected/inline script run and defeat it.
    assert "script-src 'self'" in csp, csp
    assert "'unsafe-inline'" not in csp.split("style-src")[0], \
        f"unsafe-inline must not weaken script-src: {csp}"
    assert "'unsafe-eval'" not in csp, csp
    assert "object-src 'none'" in csp, csp
    assert "frame-ancestors 'none'" in csp, csp
    assert "base-uri 'none'" in csp, csp
    # Chart export renders data: images; that source must be permitted.
    assert "img-src 'self' data:" in csp, csp


def test_anti_framing_and_nosniff_values():
    with TestClient(app) as c:
        h = c.get("/api/health").headers
    assert h.get("x-frame-options") == "DENY", h.get("x-frame-options")
    assert h.get("x-content-type-options") == "nosniff", h.get("x-content-type-options")
    assert h.get("referrer-policy") == "no-referrer", h.get("referrer-policy")


def test_headers_present_even_on_error_response():
    # Headers are stamped by the OUTERMOST middleware, so even a CSRF-refused 403
    # (generated by the inner middleware, never reaching a route) carries them.
    with TestClient(app) as c:
        r = c.post("/api/health", headers={"origin": "https://evil.example.com"})
        assert r.status_code == 403, r.status_code
        assert "content-security-policy" in r.headers, "error responses must be covered too"
        assert r.headers.get("x-frame-options") == "DENY"


def run():
    print("Security-headers contract:")
    check("all security headers present on an API response",
          test_all_headers_present_on_api_response)
    check("CSP is restrictive (strict script-src, no unsafe-*, framing denied)",
          test_csp_is_restrictive)
    check("anti-framing + nosniff + referrer values", test_anti_framing_and_nosniff_values)
    check("headers present even on a refused (403) response",
          test_headers_present_even_on_error_response)
    print()
    if FAILURES:
        print(f"{len(FAILURES)} contract(s) FAILED: {FAILURES}")
        sys.exit(1)
    print("ALL SECURITY-HEADERS TESTS PASSED")


if __name__ == "__main__":
    run()
