export declare class ApiError extends Error {
    status: any;
    detail: any;
    constructor(status: any, detail: any, statusText: any);
    get isUnauthenticated(): boolean;
}
export declare function setUnauthenticatedHandler(fn: any): void;
export declare const api: {
    me: () => Promise<any>;
    publicConfig: () => Promise<any>;
    version: () => Promise<any>;
    requestLink: (email: any) => Promise<any>;
    verifyInfo: (token: any) => Promise<any>;
    verify: (token: any) => Promise<any>;
    logout: () => Promise<any>;
    conversations: (q: any) => Promise<any>;
    conversation: (id: any) => Promise<any>;
    renameConversation: (id: any, title: any) => Promise<any>;
    deleteConversation: (id: any) => Promise<any>;
    csvUrl: (msgId: any) => string;
    apiKeys: () => Promise<any>;
    createApiKey: (label: any) => Promise<any>;
    relabelApiKey: (id: any, label: any) => Promise<any>;
    revokeApiKey: (id: any) => Promise<any>;
    allowlist: () => Promise<any>;
    addAllow: (email: any, note: any, is_admin: any) => Promise<any>;
    bulkAllow: (users: any) => Promise<any>;
    removeAllow: (email: any) => Promise<any>;
    setAdmin: (email: any, is_admin: any) => Promise<any>;
    bulkAllowlistAction: (action: any, emails: any) => Promise<any>;
    accessRequests: () => Promise<any>;
    denyAccessRequest: (email: any) => Promise<any>;
    bulkAccessRequests: (action: any, ids: any) => Promise<any>;
    deniedRequests: () => Promise<any>;
    clearDenial: (email: any) => Promise<any>;
    bulkClearDenials: (ids: any) => Promise<any>;
    usage: (since: any, until: any, source: any) => Promise<any>;
    attention: () => Promise<any>;
    markLogsSeen: () => Promise<any>;
    skills: () => Promise<any>;
    deleteSkill: (id: any, { muteCategory }?: {
        muteCategory?: boolean;
    }) => Promise<any>;
    patchSkill: (id: any, body: any) => Promise<any>;
    skillCategories: () => Promise<any>;
    muteSkillCategory: (token: any, muted: any) => Promise<any>;
    skillRejections: () => Promise<any>;
    deleteSkillRejection: (id: any) => Promise<any>;
    clearSkillRejections: () => Promise<any>;
    importJobs: () => Promise<any>;
    importJob: (id: any) => Promise<any>;
    importCatalog: (refresh?: boolean) => Promise<any>;
    integrateYears: (years: any) => Promise<any>;
    deintegrateYear: (startYear: any) => Promise<any>;
    allKeys: () => Promise<any>;
    createKeyFor: (email: any, label: any) => Promise<any>;
    bulkKeyAction: (action: any, ids: any) => Promise<any>;
    revokeAnyKey: (id: any) => Promise<any>;
    logs: (limit?: number, level?: string, q?: string, since?: any, until?: any) => Promise<any>;
};
export declare function streamChat({ question, conversationId, editMessageId }: {
    conversationId: any;
    editMessageId: any;
    question: any;
}, onEvent: any): Promise<void>;
